source 'https://rubygems.org'
ruby '2.2.2'

gem 'rails', '4.2.3'
gem 'foundation-datetimepicker-rails'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'sprockets-es6'
gem 'jquery-rails'
gem 'turbolinks'
gem 'bcrypt', '~> 3.1.7'
gem 'foundation-rails'
gem 'passenger'
gem 'devise'
gem 'ancestry', '~> 2.1.0'
gem 'momentjs-rails'
gem 'minitest-rails'
gem 'figaro'
gem 'net-ssh', '2.10.1.rc1'
gem 'thredded', git: 'https://github.com/jayroh/thredded.git', ref: '0621df73dda11a104f01b15b818f99ba0bdd3793'
gem 'bourbon', '4.2.3'
gem 'neat', '1.7.2'
gem 'bitters', '1.0.0'

group :development, :test do
  gem 'pry-byebug'
  gem 'web-console', '~> 2.0'
  gem 'binding_of_caller'
  gem 'better_errors'
  gem 'rspec-rails'
  gem 'factory_girl_rails'
end

group :test do
  gem 'minitest-rails-capybara'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'faker'
  gem 'shoulda-matchers'
end
